### ISSUE TITLE
[FEATURE REQUEST] TOC for the page

### ISSUE THREAD

**Issue by qbosen** [benjypng/logseq-toc-plugin#1]
Just like the plugin [todo-master](https://github.com/pengx17/logseq-plugin-todo-master), rendering can apply to sub blocks and also the whole page.

TOC for sub block may break the hierarchy. For example, I write a page first, and if I want to use TOC, I must move whole page into the TOC block.

**Comment by benjypng** [comment]
Hi! This is definitely part of the roadmap. However, the plugin API does not support watching for changes on the whole page, hence the need to still subsume it under a parent block.

Will close this issue for now as it is part of the roadmap, once the plugin API has been updated.

**Comment by laike9m** [comment]
Curious, does logseq team plan to add support for watching the whole page in plugin API ?

**Comment by benjypng** [comment]
Hi @laike9m, currently it doesn't!
