### ISSUE TITLE
Title Display and Hierarchy

### ISSUE THREAD

**Issue by Morganwan90** [benjypng/logseq-toc-plugin#13]
This plugin perfectly solves the problem of the Table of Contents (TOC), but I encountered two issues.

## 1. Hiding block attributes in titles

When I use Omnivore (and possibly in other uses), titles with block attributes are displayed in full, which makes the titles too long and the readability is low.

![截图_20240723131308](https://github.com/user-attachments/assets/c46c0b0e-aac3-47fe-9e40-168836c4245c)

I tried to solve this problem by placing the block attributes in the first block under the title, which can solve the problem of long titles.
![截图_20240723131510](https://github.com/user-attachments/assets/59a2789a-9cea-48bf-ab4d-b28094eb0906)

but this leads to inconsistency in the overall usage. take my note above as example, when I click on tags, I hope to display this block and its sub-list, but since I  moved the block attributes to the first sub-list, in linked references, it will not cover the title and its sub-blocks, but will only display the attribute block.
![截图_20240723131644](https://github.com/user-attachments/assets/3e2d6198-7bfd-43a6-bc89-ad26e8fd4340)

So I hope the TOC plugin can consider hiding the block attributes after the soft line break in the title.

## 2. Partial hierarchy display issues
Taking this diary page as an example, you can see that I have two third-level titles, which should be at the same level, but in TOC, the second title is displayed as the next level.

![截图_20240723132129](https://github.com/user-attachments/assets/b24b808b-88a3-4d0a-b274-b92be4168db4)

**Comment by mlhiter** [comment]
+1.

**Comment by mlhiter** [comment]
@Morganwan90 Hi,I create a PR solved it.

**Comment by Morganwan90** [comment]
> @Morganwan90 Hi,I create a PR solved it.

its soooooooo perfect!!!! thank you !
