### ISSUE TITLE
Custom css rules applied to table of contents aren't persisted across sessions

### ISSUE THREAD

**Issue by smoens** [benjypng/logseq-toc-plugin#2]
**Describe the bug**

**To Reproduce**
1. Go to 'custom.css' file of the specific graph
2. Add custom css rules to modify table of content style
e.g. red border
```
.tocBoard {
  display: flex;
  flex-direction: column;
  padding: 1em;
  border: 1px solid #FF0000;
}
```
The custom.css reloads and shows the changed style until the graph is closed again. After closing and reopening the logseq graph the changes are lost even though they are saved in the custom.css file.

**Expected behavior**
As described in [logseq-toc-plugin#changing-colours](https://github.com/hkgnp/logseq-toc-plugin#changing-colours) styling of table of contents should inherit styles as defined in custom.css and be persisted across sessions.

**Screenshots**
Custom styling rule for .tocBoard as defined in the custom.css is ignored
![image](https://user-images.githubusercontent.com/1371244/153720033-67e3cec7-8c6e-49ad-93f0-890194f0426d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Logseq Version: 0.5.9

**Comment by benjypng** [comment]
Hi! I updated the instructions.

For the attributes you want to change you need to add the `!important` flag. E.g:

```
.tocBoard {
    border: 1px solid #FF0000 !important;
}
```

**Comment by smoens** [comment]
Thank you for your quick feedback! This indeed solved the issue.
