### ISSUE TITLE
toc plugin will clear up some sub-blocks

### ISSUE THREAD

**Issue by charliie-dev** [benjypng/logseq-toc-plugin#3]
Hi, I'm using ver 0.6.1 on Win10. I found out that the toc plugin will randomly eat up some sub-blocks under the toc parent blocks after collapsing and expanding. 
Fortunately, this action will also create a duplicate file before action, so there is still some ways to revert the action.
Is there any conflictions between the plugin and the 0.6.1 version?

**Comment by benjypng** [comment]
Hmm, I am not sure what you mean. The toc plugin, as far as I can remember, does not manipulate any blocks.

Do you have a video to share what you mean?

**Comment by charliie-dev** [comment]
Strangely, after I install the [20220225 pre-realse version](https://github.com/logseq/logseq/releases/tag/nightly), this problem just gone. The plugin just work like what u demo in the readme.
Sorry for bothering you.
