### ISSUE TITLE
Can this plugin locate the place when clicking on the title in table of tables?

### ISSUE THREAD

**Issue by MooreManor** [benjypng/logseq-toc-plugin#4]
It seems that this plugin will open a new page for the block when clicking on the title in ***Table of Contents***. Can it jump to the place in the original page like Typora outline instead of opening a new page?

**Typora:**
![image](https://user-images.githubusercontent.com/49632327/163712406-a08d0dab-8ad1-4d7e-882e-c0fd054e319c.png)
**Jump instead of opening a newpage:**
![image](https://user-images.githubusercontent.com/49632327/163712394-34504e8c-18f3-4bb8-bf38-683f069a3917.png)

**Comment by benjypng** [comment]
Available in v1.5.1. Just remove the checkbox in the plugin settings!
