### ISSUE TITLE
Table of contents contains `id:: ` property

### ISSUE THREAD

**Issue by JakobBruenker** [benjypng/logseq-toc-plugin#5]
Once a block reference to a headline is created, the table of contents is cluttered up by the UUID of that block. Example:

![image](https://user-images.githubusercontent.com/10101851/173252905-6a216627-0450-4433-a198-17bcab62dbab.png)

**Comment by benjypng** [comment]
Please try in v1.5.2. Should be fixed.

**Comment by JakobBruenker** [comment]
Indeed! Thank you
